### ISSUE TITLE
Inheritance other way a round

### ISSUE THREAD

**Issue by cbl** [herrmanno/react-class-container#14]
Can't the design problem be solved by simply building the inheritance of the classes the other way around?

```js
// mycomponent.js

class MyContainer extends MyContainer {
  render(props) {
    return <span>{this.props.greeting}</span>;
  }
}

```

```js
// mycontainer.js

class MyContainer extends React.Component {
  getChildProps(props, state) {
    return { greeting: "foo" }
  }
}
```

**Comment by herrmanno** [comment]
Two problems:
- representational components are no longer 'just plain compents', because the extend a special super class
- you loose the composition of a container that _has_ a presentation component (not _is_ one). Therefore managing and accumulating state and props, that flow to the presentational component is not possible, as well as caching of (computed) props, the child shall receive. So reducing unneeded render cycles on the child would be lost.

Anyway, thanks for the food for thought.

**Comment by cbl** [comment]
I see, thanks for the description.
